import React from 'react';
import { Block, DrawingStroke, DrawingPoint } from '../../../types/editor';
import { RemoteDrawingBlockState, ExerciseActiveUser, RemoteExerciseInteraction } from '../../../hooks/editor/useLessonCollaboration';
import type { ExerciseResultData } from '../../../api/exerciseResults';

export interface BlockRendererProps {
  block: Block;
  index: number;
  contentRef: React.RefObject<HTMLElement | null>;
  baseClasses: string;
  contentProps: {
    ref: React.RefObject<HTMLElement | null>;
    contentEditable: boolean;
    suppressContentEditableWarning: boolean;
    'data-block-id': string;
    onInput: (e: React.FormEvent<HTMLDivElement>) => void;
    onPaste: (e: React.ClipboardEvent<HTMLDivElement>) => void;
    onBlur: () => void;
    onFocus: () => void;
    onKeyDown: (e: React.KeyboardEvent) => void;
    className: string;
  };
  onCheckToggle?: (id: string, checked: boolean) => void;
  onUpdateBlock?: (id: string, updatedBlock: Block) => void;
  onImageUpload?: (id: string, fileOrUrl: File | string) => void;
  onImageDelete?: (id: string) => void;
  onImageDuplicate?: (id: string) => void;
  onImageResize?: (id: string, width: number, height: number) => void;
  onImageAlignmentChange?: (id: string, alignment: 'left' | 'center' | 'right') => void;
  onDrawingUpdate?: (id: string, drawingData: any) => void;
  onDrawingStrokeProgress?: (blockId: string, points: DrawingPoint[], color: string, thickness: number) => void;
  onDrawingStrokeComplete?: (blockId: string, stroke: DrawingStroke) => void;
  onDrawingAction?: (blockId: string, strokes: DrawingStroke[]) => void;
  remoteDrawingBlockState?: RemoteDrawingBlockState;
  onVideoUpload?: (id: string, file: File) => void;
  videoUploadProgress?: number | null;
  onVideoDelete?: (id: string) => void;
  onVideoResize?: (id: string, width: number, height: number) => void;
  onVideoAlignmentChange?: (id: string, alignment: 'left' | 'center' | 'right') => void;
  onVideoDuplicate?: (id: string) => void;
  onAudioUpload?: (id: string, file: File) => void;
  onAudioDelete?: (id: string) => void;
  onPdfUpload?: (id: string, file: File) => void;
  onPdfDelete?: (id: string) => void;
  onPdfResize?: (id: string, width: number, height: number) => void;
  onPdfAlignmentChange?: (id: string, alignment: 'left' | 'center' | 'right') => void;
  onPdfDuplicate?: (id: string) => void;
  onKeyDown: (e: React.KeyboardEvent, blockId: string, index: number) => void;
  allBlocks?: Block[];
  getDisplayNumber?: () => number;
  theme?: 'light' | 'dark';
  imageWidth?: number | null;
  setIsImageWidth?: (width: number | null) => void;
  isResizing?: boolean;
  setIsResizing?: (resizing: boolean) => void;
  imageRef?: React.RefObject<HTMLImageElement | HTMLIFrameElement | null>;
  fileInputRef?: React.RefObject<HTMLInputElement | null>;
  checkboxRef?: React.RefObject<HTMLInputElement | null>;
  triggerFileInput?: () => void;
  handleFileSelect?: (e: React.ChangeEvent<HTMLInputElement>) => void;
  handleDeleteImage?: () => void;
  handleResizeStart?: (e: React.MouseEvent, corner: 'tl' | 'tr' | 'bl' | 'br' | 'r' | 'l') => void;
  setIsFocused?: (focused: boolean) => void;
  isFirst?: boolean;
  isSelected?: boolean;
  isSelecting?: boolean;
  isUploading?: boolean;
  exerciseId?: number;
  exerciseSavedResult?: ExerciseResultData;
  onExerciseResultSubmit?: (result: Omit<ExerciseResultData, 'completedAt'>) => void;
  exerciseReadOnly?: boolean;
  activeExerciseUsers?: ExerciseActiveUser[];
  remoteExerciseInteractions?: RemoteExerciseInteraction[];
  onExerciseInteractionChange?: (state: any) => void;
  onExerciseFocus?: () => void;
  onExerciseBlur?: () => void;
}

